# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/traps/view/ui/graph.ui'
#
# Created: Mon Mar  5 02:46:19 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(753, 498)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_11 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setText(QtGui.QApplication.translate("Form", "X Axis:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_9.addWidget(self.label_11)
        self.x_unit_type_box = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_unit_type_box.sizePolicy().hasHeightForWidth())
        self.x_unit_type_box.setSizePolicy(sizePolicy)
        self.x_unit_type_box.setObjectName(_fromUtf8("x_unit_type_box"))
        self.x_unit_type_box.addItem(_fromUtf8(""))
        self.x_unit_type_box.setItemText(0, QtGui.QApplication.translate("Form", "Wavelength", None, QtGui.QApplication.UnicodeUTF8))
        self.x_unit_type_box.addItem(_fromUtf8(""))
        self.x_unit_type_box.setItemText(1, QtGui.QApplication.translate("Form", "Wavenumber", None, QtGui.QApplication.UnicodeUTF8))
        self.x_unit_type_box.addItem(_fromUtf8(""))
        self.x_unit_type_box.setItemText(2, QtGui.QApplication.translate("Form", "Energy", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_9.addWidget(self.x_unit_type_box)
        self.label_12 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setText(QtGui.QApplication.translate("Form", "in", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_9.addWidget(self.label_12)
        self.stackedWidget = QtGui.QStackedWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_3 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_3.sizePolicy().hasHeightForWidth())
        self.page_3.setSizePolicy(sizePolicy)
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.page_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.wavelength_units = QtGui.QComboBox(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wavelength_units.sizePolicy().hasHeightForWidth())
        self.wavelength_units.setSizePolicy(sizePolicy)
        self.wavelength_units.setObjectName(_fromUtf8("wavelength_units"))
        self.wavelength_units.addItem(_fromUtf8(""))
        self.wavelength_units.setItemText(0, QtGui.QApplication.translate("Form", "Nanometres", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelength_units.addItem(_fromUtf8(""))
        self.wavelength_units.setItemText(1, QtGui.QApplication.translate("Form", "Metres", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelength_units.addItem(_fromUtf8(""))
        self.wavelength_units.setItemText(2, QtGui.QApplication.translate("Form", "Angstroms", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelength_units.addItem(_fromUtf8(""))
        self.wavelength_units.setItemText(3, QtGui.QApplication.translate("Form", "Furlongs", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_2.addWidget(self.wavelength_units)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page.sizePolicy().hasHeightForWidth())
        self.page.setSizePolicy(sizePolicy)
        self.page.setObjectName(_fromUtf8("page"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.wavenumber_units = QtGui.QComboBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wavenumber_units.sizePolicy().hasHeightForWidth())
        self.wavenumber_units.setSizePolicy(sizePolicy)
        self.wavenumber_units.setObjectName(_fromUtf8("wavenumber_units"))
        self.wavenumber_units.addItem(_fromUtf8(""))
        self.wavenumber_units.setItemText(0, QtGui.QApplication.translate("Form", "Inverse Nanometres", None, QtGui.QApplication.UnicodeUTF8))
        self.wavenumber_units.addItem(_fromUtf8(""))
        self.wavenumber_units.setItemText(1, QtGui.QApplication.translate("Form", "Inverse Metres", None, QtGui.QApplication.UnicodeUTF8))
        self.wavenumber_units.addItem(_fromUtf8(""))
        self.wavenumber_units.setItemText(2, QtGui.QApplication.translate("Form", "Inverse Angstroms", None, QtGui.QApplication.UnicodeUTF8))
        self.wavenumber_units.addItem(_fromUtf8(""))
        self.wavenumber_units.setItemText(3, QtGui.QApplication.translate("Form", "Inverse Furlongs", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_6.addWidget(self.wavenumber_units)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_2.sizePolicy().hasHeightForWidth())
        self.page_2.setSizePolicy(sizePolicy)
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.page_2)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.energy_units = QtGui.QComboBox(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.energy_units.sizePolicy().hasHeightForWidth())
        self.energy_units.setSizePolicy(sizePolicy)
        self.energy_units.setObjectName(_fromUtf8("energy_units"))
        self.energy_units.addItem(_fromUtf8(""))
        self.energy_units.setItemText(0, QtGui.QApplication.translate("Form", "Electron Volts", None, QtGui.QApplication.UnicodeUTF8))
        self.energy_units.addItem(_fromUtf8(""))
        self.energy_units.setItemText(1, QtGui.QApplication.translate("Form", "Joules", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_11.addWidget(self.energy_units)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_9.addWidget(self.stackedWidget)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.label = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText(QtGui.QApplication.translate("Form", "Y Axis from", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_9.addWidget(self.label)
        self.lowerY = QtGui.QDoubleSpinBox(Form)
        self.lowerY.setDecimals(1)
        self.lowerY.setMaximum(70000.0)
        self.lowerY.setObjectName(_fromUtf8("lowerY"))
        self.horizontalLayout_9.addWidget(self.lowerY)
        self.label_2 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText(QtGui.QApplication.translate("Form", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_9.addWidget(self.label_2)
        self.upperY = QtGui.QDoubleSpinBox(Form)
        self.upperY.setDecimals(1)
        self.upperY.setMaximum(70000.0)
        self.upperY.setSingleStep(100.0)
        self.upperY.setProperty("value", 10.0)
        self.upperY.setObjectName(_fromUtf8("upperY"))
        self.horizontalLayout_9.addWidget(self.upperY)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.mplWidget = MplWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplWidget.sizePolicy().hasHeightForWidth())
        self.mplWidget.setSizePolicy(sizePolicy)
        self.mplWidget.setMinimumSize(QtCore.QSize(100, 100))
        self.mplWidget.setObjectName(_fromUtf8("mplWidget"))
        self.verticalLayout.addWidget(self.mplWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.widget = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 130))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.treeWidget = QtGui.QTreeWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.treeWidget.setItemsExpandable(False)
        self.treeWidget.setAnimated(False)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("Form", "Label", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(1, QtGui.QApplication.translate("Form", "Equation", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(2, QtGui.QApplication.translate("Form", "Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout.addWidget(self.treeWidget)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.addViewButton = QtGui.QPushButton(self.widget)
        self.addViewButton.setText(QtGui.QApplication.translate("Form", "Add view", None, QtGui.QApplication.UnicodeUTF8))
        self.addViewButton.setObjectName(_fromUtf8("addViewButton"))
        self.verticalLayout_2.addWidget(self.addViewButton)
        self.removeViewButton = QtGui.QPushButton(self.widget)
        self.removeViewButton.setText(QtGui.QApplication.translate("Form", "Remove view", None, QtGui.QApplication.UnicodeUTF8))
        self.removeViewButton.setObjectName(_fromUtf8("removeViewButton"))
        self.verticalLayout_2.addWidget(self.removeViewButton)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.exportSelected = QtGui.QPushButton(self.widget)
        self.exportSelected.setText(QtGui.QApplication.translate("Form", "Export selected", None, QtGui.QApplication.UnicodeUTF8))
        self.exportSelected.setObjectName(_fromUtf8("exportSelected"))
        self.verticalLayout_2.addWidget(self.exportSelected)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.widget)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.x_unit_type_box, QtCore.SIGNAL(_fromUtf8("activated(int)")), self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

from mplwidget import MplWidget
