# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/traps/view/ui/hardware.ui'
#
# Created: Mon Mar  5 02:46:19 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(400, 745)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_2 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_10 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setText(QtGui.QApplication.translate("Form", "Integration Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_4.addWidget(self.label_10)
        self.integrationTime = QtGui.QSpinBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.integrationTime.sizePolicy().hasHeightForWidth())
        self.integrationTime.setSizePolicy(sizePolicy)
        self.integrationTime.setSuffix(QtGui.QApplication.translate("Form", " ms", None, QtGui.QApplication.UnicodeUTF8))
        self.integrationTime.setMinimum(4)
        self.integrationTime.setMaximum(1000)
        self.integrationTime.setObjectName(_fromUtf8("integrationTime"))
        self.horizontalLayout_4.addWidget(self.integrationTime)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.livePoll = QtGui.QCheckBox(Form)
        self.livePoll.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.livePoll.sizePolicy().hasHeightForWidth())
        self.livePoll.setSizePolicy(sizePolicy)
        self.livePoll.setText(QtGui.QApplication.translate("Form", "Auto-Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.livePoll.setChecked(True)
        self.livePoll.setObjectName(_fromUtf8("livePoll"))
        self.horizontalLayout.addWidget(self.livePoll)
        self.widget = QtGui.QWidget(Form)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_4 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setText(QtGui.QApplication.translate("Form", "Every", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_12.addWidget(self.label_4)
        self.livePollRate = QtGui.QSpinBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.livePollRate.sizePolicy().hasHeightForWidth())
        self.livePollRate.setSizePolicy(sizePolicy)
        self.livePollRate.setSuffix(QtGui.QApplication.translate("Form", " ms", None, QtGui.QApplication.UnicodeUTF8))
        self.livePollRate.setMinimum(10)
        self.livePollRate.setMaximum(5000)
        self.livePollRate.setProperty("value", 500)
        self.livePollRate.setObjectName(_fromUtf8("livePollRate"))
        self.horizontalLayout_12.addWidget(self.livePollRate)
        self.horizontalLayout.addWidget(self.widget)
        self.livePollButton = QtGui.QPushButton(Form)
        self.livePollButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.livePollButton.sizePolicy().hasHeightForWidth())
        self.livePollButton.setSizePolicy(sizePolicy)
        self.livePollButton.setText(QtGui.QApplication.translate("Form", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.livePollButton.setObjectName(_fromUtf8("livePollButton"))
        self.horizontalLayout.addWidget(self.livePollButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.calibLabel = QtGui.QLabel(Form)
        self.calibLabel.setText(QtGui.QApplication.translate("Form", "No temperature calibration loaded", None, QtGui.QApplication.UnicodeUTF8))
        self.calibLabel.setObjectName(_fromUtf8("calibLabel"))
        self.horizontalLayout_13.addWidget(self.calibLabel)
        self.loadCalibButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadCalibButton.sizePolicy().hasHeightForWidth())
        self.loadCalibButton.setSizePolicy(sizePolicy)
        self.loadCalibButton.setText(QtGui.QApplication.translate("Form", "Change curve", None, QtGui.QApplication.UnicodeUTF8))
        self.loadCalibButton.setObjectName(_fromUtf8("loadCalibButton"))
        self.horizontalLayout_13.addWidget(self.loadCalibButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.aquireDataSetBox = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aquireDataSetBox.sizePolicy().hasHeightForWidth())
        self.aquireDataSetBox.setSizePolicy(sizePolicy)
        self.aquireDataSetBox.setTitle(QtGui.QApplication.translate("Form", "Aquire Dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.aquireDataSetBox.setObjectName(_fromUtf8("aquireDataSetBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.aquireDataSetBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_13 = QtGui.QLabel(self.aquireDataSetBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setText(QtGui.QApplication.translate("Form", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.aquireDataSetBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setText(QtGui.QApplication.translate("Form", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.notesEditor = QtGui.QTextEdit(self.aquireDataSetBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesEditor.sizePolicy().hasHeightForWidth())
        self.notesEditor.setSizePolicy(sizePolicy)
        self.notesEditor.setMinimumSize(QtCore.QSize(20, 50))
        self.notesEditor.setMaximumSize(QtCore.QSize(200, 16777215))
        self.notesEditor.setTabStopWidth(80)
        self.notesEditor.setObjectName(_fromUtf8("notesEditor"))
        self.gridLayout.addWidget(self.notesEditor, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.dataSetComboBox = QtGui.QComboBox(self.aquireDataSetBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataSetComboBox.sizePolicy().hasHeightForWidth())
        self.dataSetComboBox.setSizePolicy(sizePolicy)
        self.dataSetComboBox.setEditable(True)
        self.dataSetComboBox.setInsertPolicy(QtGui.QComboBox.InsertAtTop)
        self.dataSetComboBox.setObjectName(_fromUtf8("dataSetComboBox"))
        self.horizontalLayout_2.addWidget(self.dataSetComboBox)
        self.addDataSet = QtGui.QToolButton(self.aquireDataSetBox)
        self.addDataSet.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.addDataSet.setObjectName(_fromUtf8("addDataSet"))
        self.horizontalLayout_2.addWidget(self.addDataSet)
        self.deleteDataSet = QtGui.QToolButton(self.aquireDataSetBox)
        self.deleteDataSet.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteDataSet.setObjectName(_fromUtf8("deleteDataSet"))
        self.horizontalLayout_2.addWidget(self.deleteDataSet)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.tempTriggerCheckBox = QtGui.QCheckBox(self.aquireDataSetBox)
        self.tempTriggerCheckBox.setText(QtGui.QApplication.translate("Form", "Trigger By Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.tempTriggerCheckBox.setObjectName(_fromUtf8("tempTriggerCheckBox"))
        self.verticalLayout.addWidget(self.tempTriggerCheckBox)
        self.tempControlWidget = QtGui.QWidget(self.aquireDataSetBox)
        self.tempControlWidget.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempControlWidget.sizePolicy().hasHeightForWidth())
        self.tempControlWidget.setSizePolicy(sizePolicy)
        self.tempControlWidget.setObjectName(_fromUtf8("tempControlWidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tempControlWidget)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.currentTempSlider = QtGui.QSlider(self.tempControlWidget)
        self.currentTempSlider.setEnabled(False)
        self.currentTempSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.currentTempSlider.setMaximum(280)
        self.currentTempSlider.setTracking(False)
        self.currentTempSlider.setOrientation(QtCore.Qt.Vertical)
        self.currentTempSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.currentTempSlider.setTickInterval(5)
        self.currentTempSlider.setObjectName(_fromUtf8("currentTempSlider"))
        self.horizontalLayout_7.addWidget(self.currentTempSlider)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_9 = QtGui.QLabel(self.tempControlWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setText(QtGui.QApplication.translate("Form", "Highest temperature = ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_3.addWidget(self.label_9)
        self.trigMax = QtGui.QSpinBox(self.tempControlWidget)
        self.trigMax.setSuffix(QtGui.QApplication.translate("Form", " K", None, QtGui.QApplication.UnicodeUTF8))
        self.trigMax.setMaximum(330)
        self.trigMax.setProperty("value", 280)
        self.trigMax.setObjectName(_fromUtf8("trigMax"))
        self.horizontalLayout_3.addWidget(self.trigMax)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_15 = QtGui.QLabel(self.tempControlWidget)
        self.label_15.setText(QtGui.QApplication.translate("Form", "Take", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_5.addWidget(self.label_15)
        self.trigSteps = QtGui.QSpinBox(self.tempControlWidget)
        self.trigSteps.setProperty("value", 29)
        self.trigSteps.setObjectName(_fromUtf8("trigSteps"))
        self.horizontalLayout_5.addWidget(self.trigSteps)
        self.label_7 = QtGui.QLabel(self.tempControlWidget)
        self.label_7.setText(QtGui.QApplication.translate("Form", "spectra", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.tempControlWidget)
        self.label_6.setText(QtGui.QApplication.translate("Form", "(one every", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.trigDelta = QtGui.QDoubleSpinBox(self.tempControlWidget)
        self.trigDelta.setSuffix(QtGui.QApplication.translate("Form", " K", None, QtGui.QApplication.UnicodeUTF8))
        self.trigDelta.setMaximum(280.0)
        self.trigDelta.setProperty("value", 10.0)
        self.trigDelta.setObjectName(_fromUtf8("trigDelta"))
        self.horizontalLayout_8.addWidget(self.trigDelta)
        self.label_16 = QtGui.QLabel(self.tempControlWidget)
        self.label_16.setText(QtGui.QApplication.translate("Form", ")", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_8.addWidget(self.label_16)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_13.addLayout(self.horizontalLayout_8)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem6)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_8 = QtGui.QLabel(self.tempControlWidget)
        self.label_8.setText(QtGui.QApplication.translate("Form", "Lowest Temperature = ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_10.addWidget(self.label_8)
        self.trigMin = QtGui.QSpinBox(self.tempControlWidget)
        self.trigMin.setReadOnly(False)
        self.trigMin.setSuffix(QtGui.QApplication.translate("Form", " K", None, QtGui.QApplication.UnicodeUTF8))
        self.trigMin.setMaximum(280)
        self.trigMin.setObjectName(_fromUtf8("trigMin"))
        self.horizontalLayout_10.addWidget(self.trigMin)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7.addLayout(self.verticalLayout_13)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.tempControlWidget)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_5 = QtGui.QLabel(self.aquireDataSetBox)
        self.label_5.setText(QtGui.QApplication.translate("Form", "Current T = ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_11.addWidget(self.label_5)
        self.currentTempText = QtGui.QLabel(self.aquireDataSetBox)
        self.currentTempText.setText(QtGui.QApplication.translate("Form", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.currentTempText.setObjectName(_fromUtf8("currentTempText"))
        self.horizontalLayout_11.addWidget(self.currentTempText)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.aquireButton = QtGui.QPushButton(self.aquireDataSetBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aquireButton.sizePolicy().hasHeightForWidth())
        self.aquireButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.aquireButton.setFont(font)
        self.aquireButton.setText(QtGui.QApplication.translate("Form", "Aquire!", None, QtGui.QApplication.UnicodeUTF8))
        self.aquireButton.setObjectName(_fromUtf8("aquireButton"))
        self.verticalLayout.addWidget(self.aquireButton)
        self.verticalLayout_2.addWidget(self.aquireDataSetBox)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.livePoll, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.widget.setVisible)
        QtCore.QObject.connect(self.livePoll, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.livePollButton.setHidden)
        QtCore.QObject.connect(self.tempTriggerCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.tempControlWidget.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

