# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/calib/view/ui/calib.ui'
#
# Created: Mon Mar  5 02:46:19 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(841, 727)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Calibrated device", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.calibLabel = QtGui.QLabel(self.groupBox)
        self.calibLabel.setText(QtGui.QApplication.translate("Form", "No curve loaded", None, QtGui.QApplication.UnicodeUTF8))
        self.calibLabel.setObjectName(_fromUtf8("calibLabel"))
        self.horizontalLayout.addWidget(self.calibLabel)
        self.loadCalibButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadCalibButton.sizePolicy().hasHeightForWidth())
        self.loadCalibButton.setSizePolicy(sizePolicy)
        self.loadCalibButton.setText(QtGui.QApplication.translate("Form", "Change curve", None, QtGui.QApplication.UnicodeUTF8))
        self.loadCalibButton.setObjectName(_fromUtf8("loadCalibButton"))
        self.horizontalLayout.addWidget(self.loadCalibButton)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.widget)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Calibrate from comparative data", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.loadComparitiveDataButton = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadComparitiveDataButton.sizePolicy().hasHeightForWidth())
        self.loadComparitiveDataButton.setSizePolicy(sizePolicy)
        self.loadComparitiveDataButton.setText(QtGui.QApplication.translate("Form", "Load data", None, QtGui.QApplication.UnicodeUTF8))
        self.loadComparitiveDataButton.setFlat(False)
        self.loadComparitiveDataButton.setObjectName(_fromUtf8("loadComparitiveDataButton"))
        self.horizontalLayout_2.addWidget(self.loadComparitiveDataButton)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.widget)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Calibrate from voltage input", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.calDevInput = QtGui.QComboBox(self.groupBox_2)
        self.calDevInput.setObjectName(_fromUtf8("calDevInput"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.calDevInput)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setText(QtGui.QApplication.translate("Form", "New device input", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.newDevInput = QtGui.QComboBox(self.groupBox_2)
        self.newDevInput.setObjectName(_fromUtf8("newDevInput"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.newDevInput)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setText(QtGui.QApplication.translate("Form", "Calibrated device input", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.tempTriggerCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.tempTriggerCheckBox.setText(QtGui.QApplication.translate("Form", "Trigger By Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.tempTriggerCheckBox.setCheckable(True)
        self.tempTriggerCheckBox.setChecked(True)
        self.tempTriggerCheckBox.setObjectName(_fromUtf8("tempTriggerCheckBox"))
        self.verticalLayout.addWidget(self.tempTriggerCheckBox)
        self.tempControlWidget = QtGui.QWidget(self.groupBox_2)
        self.tempControlWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempControlWidget.sizePolicy().hasHeightForWidth())
        self.tempControlWidget.setSizePolicy(sizePolicy)
        self.tempControlWidget.setObjectName(_fromUtf8("tempControlWidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tempControlWidget)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.currentTempSlider = QtGui.QSlider(self.tempControlWidget)
        self.currentTempSlider.setEnabled(False)
        self.currentTempSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.currentTempSlider.setMaximum(280)
        self.currentTempSlider.setTracking(False)
        self.currentTempSlider.setOrientation(QtCore.Qt.Vertical)
        self.currentTempSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.currentTempSlider.setTickInterval(5)
        self.currentTempSlider.setObjectName(_fromUtf8("currentTempSlider"))
        self.horizontalLayout_7.addWidget(self.currentTempSlider)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_9 = QtGui.QLabel(self.tempControlWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setText(QtGui.QApplication.translate("Form", "Highest temperature = ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_3.addWidget(self.label_9)
        self.trigMax = QtGui.QSpinBox(self.tempControlWidget)
        self.trigMax.setSuffix(QtGui.QApplication.translate("Form", " K", None, QtGui.QApplication.UnicodeUTF8))
        self.trigMax.setMaximum(330)
        self.trigMax.setProperty("value", 280)
        self.trigMax.setObjectName(_fromUtf8("trigMax"))
        self.horizontalLayout_3.addWidget(self.trigMax)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_13.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_15 = QtGui.QLabel(self.tempControlWidget)
        self.label_15.setText(QtGui.QApplication.translate("Form", "Take", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_5.addWidget(self.label_15)
        self.trigSteps = QtGui.QSpinBox(self.tempControlWidget)
        self.trigSteps.setProperty("value", 29)
        self.trigSteps.setObjectName(_fromUtf8("trigSteps"))
        self.horizontalLayout_5.addWidget(self.trigSteps)
        self.label_7 = QtGui.QLabel(self.tempControlWidget)
        self.label_7.setText(QtGui.QApplication.translate("Form", "readings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.tempControlWidget)
        self.label_6.setText(QtGui.QApplication.translate("Form", "(one every", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.trigDelta = QtGui.QDoubleSpinBox(self.tempControlWidget)
        self.trigDelta.setSuffix(QtGui.QApplication.translate("Form", " K", None, QtGui.QApplication.UnicodeUTF8))
        self.trigDelta.setMaximum(280.0)
        self.trigDelta.setProperty("value", 10.0)
        self.trigDelta.setObjectName(_fromUtf8("trigDelta"))
        self.horizontalLayout_8.addWidget(self.trigDelta)
        self.label_16 = QtGui.QLabel(self.tempControlWidget)
        self.label_16.setText(QtGui.QApplication.translate("Form", ")", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_8.addWidget(self.label_16)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_13.addLayout(self.horizontalLayout_8)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem4)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_8 = QtGui.QLabel(self.tempControlWidget)
        self.label_8.setText(QtGui.QApplication.translate("Form", "Lowest Temperature = ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_10.addWidget(self.label_8)
        self.trigMin = QtGui.QSpinBox(self.tempControlWidget)
        self.trigMin.setReadOnly(False)
        self.trigMin.setSuffix(QtGui.QApplication.translate("Form", " K", None, QtGui.QApplication.UnicodeUTF8))
        self.trigMin.setMaximum(280)
        self.trigMin.setObjectName(_fromUtf8("trigMin"))
        self.horizontalLayout_10.addWidget(self.trigMin)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7.addLayout(self.verticalLayout_13)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.tempControlWidget)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setText(QtGui.QApplication.translate("Form", "Current T = ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_12.addWidget(self.label_5)
        self.currentTempText = QtGui.QLabel(self.groupBox_2)
        self.currentTempText.setText(QtGui.QApplication.translate("Form", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.currentTempText.setObjectName(_fromUtf8("currentTempText"))
        self.horizontalLayout_12.addWidget(self.currentTempText)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.aquireButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aquireButton.sizePolicy().hasHeightForWidth())
        self.aquireButton.setSizePolicy(sizePolicy)
        self.aquireButton.setText(QtGui.QApplication.translate("Form", "Aquire calibration data", None, QtGui.QApplication.UnicodeUTF8))
        self.aquireButton.setObjectName(_fromUtf8("aquireButton"))
        self.verticalLayout.addWidget(self.aquireButton)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.widget1 = QtGui.QWidget(self.splitter)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.label_3 = QtGui.QLabel(self.widget1)
        self.label_3.setText(QtGui.QApplication.translate("Form", "Show temperature from ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_9.addWidget(self.label_3)
        self.minTempAxis = QtGui.QDoubleSpinBox(self.widget1)
        self.minTempAxis.setSuffix(QtGui.QApplication.translate("Form", " K", None, QtGui.QApplication.UnicodeUTF8))
        self.minTempAxis.setDecimals(1)
        self.minTempAxis.setMaximum(330.0)
        self.minTempAxis.setProperty("value", 0.0)
        self.minTempAxis.setObjectName(_fromUtf8("minTempAxis"))
        self.horizontalLayout_9.addWidget(self.minTempAxis)
        self.label_4 = QtGui.QLabel(self.widget1)
        self.label_4.setText(QtGui.QApplication.translate("Form", " to ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_9.addWidget(self.label_4)
        self.maxTempAxis = QtGui.QDoubleSpinBox(self.widget1)
        self.maxTempAxis.setSuffix(QtGui.QApplication.translate("Form", " K", None, QtGui.QApplication.UnicodeUTF8))
        self.maxTempAxis.setDecimals(1)
        self.maxTempAxis.setMaximum(330.0)
        self.maxTempAxis.setProperty("value", 330.0)
        self.maxTempAxis.setObjectName(_fromUtf8("maxTempAxis"))
        self.horizontalLayout_9.addWidget(self.maxTempAxis)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.mplWidget = MplWidget(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplWidget.sizePolicy().hasHeightForWidth())
        self.mplWidget.setSizePolicy(sizePolicy)
        self.mplWidget.setMinimumSize(QtCore.QSize(100, 100))
        self.mplWidget.setAutoFillBackground(False)
        self.mplWidget.setObjectName(_fromUtf8("mplWidget"))
        self.verticalLayout_3.addWidget(self.mplWidget)
        self.tabWidget = QtGui.QTabWidget(self.widget1)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.showCalCurveButton = QtGui.QCheckBox(self.tab)
        self.showCalCurveButton.setText(QtGui.QApplication.translate("Form", "Show on graph", None, QtGui.QApplication.UnicodeUTF8))
        self.showCalCurveButton.setChecked(True)
        self.showCalCurveButton.setObjectName(_fromUtf8("showCalCurveButton"))
        self.verticalLayout_4.addWidget(self.showCalCurveButton)
        self.calTreeWidget = SeparableTreeWidget(self.tab)
        self.calTreeWidget.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.calTreeWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.calTreeWidget.setAutoExpandDelay(-1)
        self.calTreeWidget.setObjectName(_fromUtf8("calTreeWidget"))
        self.calTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("Form", "Temperature (K)", None, QtGui.QApplication.UnicodeUTF8))
        self.calTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("Form", "placeholder", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_4.addWidget(self.calTreeWidget)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.calAddSeparatorButton = QtGui.QPushButton(self.tab)
        self.calAddSeparatorButton.setText(QtGui.QApplication.translate("Form", "Add separator", None, QtGui.QApplication.UnicodeUTF8))
        self.calAddSeparatorButton.setObjectName(_fromUtf8("calAddSeparatorButton"))
        self.horizontalLayout_11.addWidget(self.calAddSeparatorButton)
        self.calDelete = QtGui.QPushButton(self.tab)
        self.calDelete.setText(QtGui.QApplication.translate("Form", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.calDelete.setObjectName(_fromUtf8("calDelete"))
        self.horizontalLayout_11.addWidget(self.calDelete)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.calSaveCurveButton = QtGui.QPushButton(self.tab)
        self.calSaveCurveButton.setText(QtGui.QApplication.translate("Form", "Save curve data", None, QtGui.QApplication.UnicodeUTF8))
        self.calSaveCurveButton.setAutoDefault(False)
        self.calSaveCurveButton.setDefault(False)
        self.calSaveCurveButton.setFlat(False)
        self.calSaveCurveButton.setObjectName(_fromUtf8("calSaveCurveButton"))
        self.horizontalLayout_11.addWidget(self.calSaveCurveButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.showNewCurveButton = QtGui.QCheckBox(self.tab_2)
        self.showNewCurveButton.setText(QtGui.QApplication.translate("Form", "Show on graph", None, QtGui.QApplication.UnicodeUTF8))
        self.showNewCurveButton.setChecked(True)
        self.showNewCurveButton.setObjectName(_fromUtf8("showNewCurveButton"))
        self.verticalLayout_5.addWidget(self.showNewCurveButton)
        self.newTreeWidget = SeparableTreeWidget(self.tab_2)
        self.newTreeWidget.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.newTreeWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.newTreeWidget.setAutoExpandDelay(-1)
        self.newTreeWidget.setObjectName(_fromUtf8("newTreeWidget"))
        self.newTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("Form", "New device voltage (mV)", None, QtGui.QApplication.UnicodeUTF8))
        self.newTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("Form", "Calibrated device placeholder", None, QtGui.QApplication.UnicodeUTF8))
        self.newTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("Form", "Temperature (K)", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_5.addWidget(self.newTreeWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.newAddSeparatorButton = QtGui.QPushButton(self.tab_2)
        self.newAddSeparatorButton.setText(QtGui.QApplication.translate("Form", "Add separator", None, QtGui.QApplication.UnicodeUTF8))
        self.newAddSeparatorButton.setObjectName(_fromUtf8("newAddSeparatorButton"))
        self.horizontalLayout_4.addWidget(self.newAddSeparatorButton)
        self.newDelete = QtGui.QPushButton(self.tab_2)
        self.newDelete.setText(QtGui.QApplication.translate("Form", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.newDelete.setObjectName(_fromUtf8("newDelete"))
        self.horizontalLayout_4.addWidget(self.newDelete)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.newSaveComparativeButton = QtGui.QPushButton(self.tab_2)
        self.newSaveComparativeButton.setText(QtGui.QApplication.translate("Form", "Save comparative data", None, QtGui.QApplication.UnicodeUTF8))
        self.newSaveComparativeButton.setAutoDefault(False)
        self.newSaveComparativeButton.setDefault(False)
        self.newSaveComparativeButton.setFlat(False)
        self.newSaveComparativeButton.setObjectName(_fromUtf8("newSaveComparativeButton"))
        self.horizontalLayout_4.addWidget(self.newSaveComparativeButton)
        self.newSaveCurveButton = QtGui.QPushButton(self.tab_2)
        self.newSaveCurveButton.setText(QtGui.QApplication.translate("Form", "Save curve data", None, QtGui.QApplication.UnicodeUTF8))
        self.newSaveCurveButton.setAutoDefault(False)
        self.newSaveCurveButton.setDefault(False)
        self.newSaveCurveButton.setFlat(False)
        self.newSaveCurveButton.setObjectName(_fromUtf8("newSaveCurveButton"))
        self.horizontalLayout_4.addWidget(self.newSaveCurveButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_6.addWidget(self.splitter)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.tempTriggerCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.tempControlWidget.setEnabled)
        QtCore.QObject.connect(self.minTempAxis, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.mplWidget.setMinTemp)
        QtCore.QObject.connect(self.maxTempAxis, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.mplWidget.setMaxTemp)
        QtCore.QObject.connect(self.showNewCurveButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.mplWidget.setNewVisible)
        QtCore.QObject.connect(self.showCalCurveButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.mplWidget.setCalVisible)
        QtCore.QObject.connect(self.newAddSeparatorButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.newTreeWidget.addSeparator)
        QtCore.QObject.connect(self.calAddSeparatorButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.calTreeWidget.addSeparator)
        QtCore.QObject.connect(self.calDelete, QtCore.SIGNAL(_fromUtf8("clicked()")), self.calTreeWidget.deleteSelected)
        QtCore.QObject.connect(self.newDelete, QtCore.SIGNAL(_fromUtf8("clicked()")), self.newTreeWidget.deleteSelected)
        QtCore.QObject.connect(self.newSaveComparativeButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.newTreeWidget.saveComparativeData)
        QtCore.QObject.connect(self.newSaveCurveButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.newTreeWidget.saveCurveData)
        QtCore.QObject.connect(self.calSaveCurveButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.calTreeWidget.saveCurveData)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Calibrated device data", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "New device data", None, QtGui.QApplication.UnicodeUTF8))

from mplwidget import MplWidget
from SeparableTreeWidget import SeparableTreeWidget
